## **Numpy**

In [ ]:
import numpy as np

In [ ]:
a=[1,2,3,4,5]
b=np.array(a)
b

array([1, 2, 3, 4, 5])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
a=[]
size=int(input("Enter size of array:"))
for i in range(size):
  val=int(input("Enter number:"))
  a.append(val)
print()
b=np.array(a)
b

Enter size of array:5
Enter number:65
Enter number:21
Enter number:95
Enter number:2
Enter number:32



array([65, 21, 95,  2, 32])

# **Two Dimensional Array**

In [ ]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print("Total Dimension:",b.ndim )
print("Shape of an array",b.shape )
print("Total Elements:",b.size )

Total Dimension: 2
Shape of an array (3, 3)
Total Elements: 9


# **How to check size and dimension of an array**

# **NUMPY FUNCTIONS**

# **1. Zeroes ==> /this function creates an array(either one dimensional or multi dimensional ) and fill all the values with zeroes**

In [ ]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
b=np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b.ndim

2

In [ ]:
a.ndim

1

# **2. Ones ==> This function creates an array (either one dimensional or multi dimensional) and fill all the values with one**

In [ ]:
a=np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [ ]:
b=np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

# **3. Eye ==> This funciton creates an array with all the diagonal elements as 1 and rest are 0(in square matrix).In non square matrix the value are still one diagonal(upto which it can draw diagonal) and rest are zero.**

In [ ]:
a=np.array(3)
a

array(3)

In [ ]:
b=np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# **4. diag ==> This function creates a two dimensional array with all the diagonal elements as the given value and rest are zero.**

In [ ]:
a= np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

# **5. randint ==> This function is used to generate a random number between a given range.**

# **SYNTAX == randint( min_value, max_value,total_numbers)**



In [ ]:
a=np.random.randint(1,10,3)
a

array([4, 5, 1])

# **rand ==> This function is used to generate a random number between 0 an 1.**

# **SYNTAX == rand(number of values)**

In [ ]:
a= np.random.rand(5)
a

array([0.40269842, 0.76738251, 0.33240009, 0.34272742, 0.28282104])

# **7. randn ==> This function is used to generate a random number from -3 to 3. This may return positive and negative number as well.**

# **SYNTAX == random.randn(number of values)**

In [ ]:
a= np.random.randn(5)
a

array([ 0.91252363,  0.12709524,  0.22261089, -1.21237439,  1.13255799])

# **Reshaping Data**

In [ ]:
# n(rows) * n(columns) = n(total_elements) ===> condition always true

In [ ]:
a= np.random.randint(1,50,12)
a

array([44, 46, 44, 36, 28, 34, 24, 28,  2, 21, 25,  2])

In [ ]:
# n(rows) * n(columns) = n(total_elements)

In [ ]:
a.shape

(12,)

In [ ]:
a.reshape(2,6)

array([[44, 46, 44, 36, 28, 34],
       [24, 28,  2, 21, 25,  2]])

In [ ]:
a.reshape(6,2)

array([[44, 46],
       [44, 36],
       [28, 34],
       [24, 28],
       [ 2, 21],
       [25,  2]])

In [ ]:
a.reshape(3,4)

array([[44, 46, 44, 36],
       [28, 34, 24, 28],
       [ 2, 21, 25,  2]])

# **Seed Function() ===> we know that randint function generates random numbers. Everytime we run the program , new set of random number is generated. So, solve this problem we will use seed function.**

In [33]:
np.random.seed(20)
a=np.random.randint(1,100,10)
a

array([91, 16, 96, 29, 91, 10, 21, 76, 23, 72])

# **View Vs Copy ==>When we slice a sub-array from an array, it may be done by two ways**

In [35]:
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6]
b[:]=0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [38]:
b

array([0, 0, 0])

# **Copy**

In [36]:
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [37]:
b

array([0, 0, 0])

# **Conditional Selection == starting value included and last value excluded**

In [39]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [41]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [42]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [ ]:
a[a%2 == 0]

In [43]:
a  = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [44]:
b  = np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [45]:
a+b

array([[ 6,  8],
       [10, 12]])

In [46]:
b-a

array([[4, 4],
       [4, 4]])

In [47]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [48]:
a*b

array([[ 5, 12],
       [21, 32]])

In [49]:
a.dot(b)

array([[19, 22],
       [43, 50]])

**np.unique(arr , return_index = True , return_counts = True)**

returns 3 array
1. the array with unique values.
2. the array with respective index value.
3. the array with counting of frequency.

In [50]:
a = np.array([10,20,30,40,10,20,50])
np.unique(a , return_index = True , return_counts = True)

(array([10, 20, 30, 40, 50]), array([0, 1, 2, 3, 6]), array([2, 2, 1, 1, 1]))

**Horizontal and Vertical Stacking**

In [51]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])
a

array([1, 2, 3, 4])

In [52]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [53]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Questions for today**

In [55]:
# Q.1 = Write statement to import numpy?

import numpy as np

In [56]:
# Q.2 Create an array using numpy?

a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [57]:
# Q.3 Create an array of 10 random integers?

a = np.random.randint(1,50,10)
a

array([35, 33, 41, 22, 27, 27, 20, 17, 39, 39])

In [58]:
# Q.4 Create an array of elements from 10-20?

a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
# Q.5 Create an array which contains value 5, 10 times?

a = np.ones(10)*5
a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [60]:
# Q.6 Create a one dimensional array and convert that into 3*3 matrix ?

a = np.array([1,2,3,4,5,6,7,8,9])
b = a.reshape(3,3)
b


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
#Q.7 Create a 2D array of size 3'3 but all the elements should be between 0 to 1?

a = np.random.rand(3,3)
a

array([[0.78300361, 0.85032764, 0.77524489],
       [0.03666431, 0.11669374, 0.7512807 ],
       [0.23921822, 0.25480601, 0.85762553]])

In [62]:
# Q.8 Concatenate 2D array horizontally and vertically?


a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
np.hstack((a))


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.vstack((a))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])